- name: Check if ripgrep is installed
  shell: command -v ripgrep >/dev/null 2>&1
  register: check_ripgrep_installed
  ignore_errors: true

- name: Download ripgrep deb archive
  get_url:
    url: "{{ ripgrep_deb.url }}"
    dest: "{{ ripgrep_deb.path }}"
    sha256sum: "{{ ripgrep_deb.sha256sum }}"
  when: check_ripgrep_installed.rc != 0

- name: Install ripgrep
  apt:
    deb: "{{ ripgrep_deb.path }}"
  become: yes
  when: check_ripgrep_installed.rc != 0
