- name: Download Golang Binary Distribution
  get_url: url={{ golang_binary_targz_url }}
           dest={{ golang_binary_targz_fullpath }}
           sha256sum={{ golang_binary_targz_sha256sum }}

- name: install Go
  shell: "tar -C /usr/local -xzf {{ golang_binary_targz_fullpath }}"

- name: append /usr/local/go to PATH env var in /etc/environment
  shell: "{{ update_etc_environment_path_path }} --folder /usr/local/go/bin"
