---
- name: Check if powerline fonts git repo exists
  shell: "test -d ~/powerline-fonts"
  ignore_errors: True
  register: check_if_powerline_fonts_git_repo_exists

- name: Clone powerline fonts git repo
  shell: "git clone https://github.com/powerline/fonts.git powerline-fonts"
  args:
    chdir: "~"
  when: check_if_powerline_fonts_git_repo_exists.rc != 0

- name: Install powerline fonts
  shell: "./install.sh"
  args:
    chdir: "~/powerline-fonts"
  when: check_if_powerline_fonts_git_repo_exists.rc != 0
