#- name: Add ffmpeg ppa
#  include: ../../../playbook-includes/add-ppa.yml
#           name=ffmpeg
#           keyserver=keyserver.ubuntu.com
#           key_fingerprint=8E51A6D660CD88D67D65221D90BD7EACED8E640A
#           deb_ppa=http://ppa.launchpad.net/mc3man/trusty-media/ubuntu
#           deb_src_ppa=http://ppa.launchpad.net/mc3man/trusty-media/ubuntu

- name: check {{ apt_sources_list }} to see if sg mirror is used
  shell: "cat {{ apt_sources_list }} | perl -ne 'print if /^(deb|deb-src) http:\\/\\/sg.archive.ubuntu.com/' | wc -l"
  register: nr_lines_with_sg_mirror_in_apt_sources

- name: replace {{ apt_sg_mirror }} mirrors with {{ apt_osuosl_mirror }} mirror
  shell: perl -pi -e 's#^(deb|deb-src) {{ apt_sg_mirror }}#\1 {{ apt_osuosl_mirror }}#' /etc/apt/sources.list
  when: nr_lines_with_sg_mirror_in_apt_sources.stdout | int > 0

- name: Check if we need to perform apt-get update (if last update was > 1 day ago OR if we just replaced apt sg mirror)
  check_if_need_to_apt_get_update: cache_valid_time=86400
                                   nr_lines_with_sg_mirror_in_apt_sources={{ nr_lines_with_sg_mirror_in_apt_sources.stdout }}
  register: ag_update
  become: yes

- name: apt-get update
  apt: update_cache="yes"
  when: ag_update.need_to_update
  become: yes

- name: install some packages
  apt: name={{ item }}
       state=present
  with_items:
    - chromium-browser
    - curl
    # get metadata of image files
    - exiftool
    - expat
    - ffmpeg
    - firefox
    - g++
    - gcc
    - gdb
    - gimp
    - git
    - gstreamer0.10-ffmpeg
    - htop
    - imagemagick
    - ipcalc
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libgmp-dev
    - liblzma-dev
    - libncurses5-dev
    - libpcre3
    - libpcre3-dev
    - libsqlite3-dev
    - libssl-dev
    - lzma-dev
    - make
    - mc    # midnight commander
    - octave
    - pwgen
    - pv
    - screen
    - scrot
    - sqlite3
    - tcl8.6
    - tcl8.6-dev
    - tk8.6
    - tk8.6-dev
    - tmux
    - unzip
    - vim
    - xclip
    - xsel
    - zlib1g-dev
    - zsh
  become: yes

- include: install-dotfiles.yml

- name: Install Haskell
  include: install-haskell.yml

- name: Install zsh-git-prompt
  include: install-zsh-git-prompt.yml

# NOTE: This part should always be placed at the end of this file because there
#       is a high chance of it failing due to network connection issues
# Installs TexLive.
- include: install-texlive.yml
