- name: check {{ apt_sources_list }} to see if sg mirror is used
  shell: "cat {{ apt_sources_list }} | perl -ne 'print if /^(deb|deb-src) http:\\/\\/sg.archive.ubuntu.com/' | wc -l"
  register: nr_lines_with_sg_mirror_in_apt_sources

- name: replace {{ apt_sg_mirror }} mirrors with {{ apt_osuosl_mirror }} mirror
  shell: perl -pi -e 's#^(deb|deb-src) {{ apt_sg_mirror }}#\1 {{ apt_osuosl_mirror }}#' /etc/apt/sources.list
  when: nr_lines_with_sg_mirror_in_apt_sources.stdout | int > 0

- name: "Add virtualbox key"
  apt_key:
    file: "{{ repo_files_path }}/oracle_vbox_2016.asc"
    id: "B9F8D658297AF3EFC18D5CDFA2F683C52980AECF"
  become: yes

- name: "Add virtualbox apt repository"
  apt_repository:
    repo: "deb https://download.virtualbox.org/virtualbox/debian bionic contrib"
  become: yes

- name: Check if we need to perform apt-get update (if last update was > 1 day ago OR if we just replaced apt sg mirror)
  check_if_need_to_apt_get_update: cache_valid_time=86400
                                   nr_lines_with_sg_mirror_in_apt_sources={{ nr_lines_with_sg_mirror_in_apt_sources.stdout }}
  register: ag_update
  become: yes

- name: apt-get update
  apt: update_cache="yes"
  when: ag_update.need_to_update
  become: yes

- name: List the packages to install
  set_fact:
    ubuntu_packages:
      - chromium-browser
      - curl
      # get metadata of image files
      - exiftool
      - expat
      - ffmpeg
      - firefox
      - g++
      - gcc
      - gdb
      - gimp
      - git
      - htop
      - imagemagick
      - iptables-persistent
      - ipcalc
      - libbz2-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
      - libgmp-dev
      - liblzma-dev
      - libncurses5-dev
      - libpcre3
      - libpcre3-dev
      - libsqlite3-dev
      - libssl-dev
      - lzma-dev
      - make
      - mc    # midnight commander
      - net-tools
      - octave
      - pwgen
      - pv
      - screen
      - scrot
      - sqlite3
      - tcl8.6
      - tcl8.6-dev
      - tk8.6
      - tk8.6-dev
      - tmux
      - unzip
      - vim
      - virtualbox-6.0
      - xclip
      - xsel
      - zlib1g-dev
      - zsh

- name: install some packages
  apt: name="{{ ubuntu_packages }}"
       state=present
  become: yes

- include: install-dotfiles.yml

- name: Install Haskell
  include: install-haskell.yml

- name: Install zsh-git-prompt
  include: install-zsh-git-prompt.yml

- name: "Install lock-screen script"
  copy:
    src: "lock-screen"
    dest: "/usr/local/bin/lock-screen"
    owner: "root"
    group: "root"
    mode: "0755"
  become: yes

- name: "Disable cups on system startup"
  systemd:
    name: "cups.service"
    enabled: no
  become: yes
  ignore_errors: yes

- name: "Install texlive"
  include: install-texlive.yml
  tags: ["never", "install_texlive"]
