- name: Download Golang Binary Distribution
  shell: "wget {{ golang_binary_targz_url }} -O {{ golang_binary_targz_fullpath }}"

- name: Compute SHA1sum of Golang Binary Distribution
  shell: "shasum -a 1 {{ golang_binary_targz_fullpath }}"
  register: golang_binary_targz_sha1sum_actual

- name: Ensure that SHA1sum of Golang Binary Distribution is correct
  assert:
    that:
      "golang_binary_targz_sha1sum_actual.stdout.split()[0] == \"{{ golang_binary_targz_sha1sum_expected }}\""

- name: install Go
  shell: "tar -C /usr/local -xzf {{ golang_binary_targz_fullpath }}"

- name: append /usr/local/go to PATH env var in /etc/environment
  shell: "{{ update_etc_environment_path_path }} --folder /usr/local/go/bin"
